begin;
set local search_path=public,extensions;
select no_plan();
-- @command-fixtures

set local role service_role;
select throws_ok($$select test_support.run('start_attempt',jsonb_build_object('scheduledChallengeId',test_support.id('sc-flash')))$$,'42501',null,'No verified identity means no command access');
reset role;
select test_support.as_actor('spectator');
set local role service_role;
select throws_ok($$select test_support.run('start_attempt',jsonb_build_object('scheduledChallengeId',test_support.id('sc-flash')))$$,'42501',null,'Spectator cannot start competitive attempt');
reset role;
select test_support.as_actor('owner');

create function test_support.fail_audit() returns trigger language plpgsql as $$
begin raise exception 'injected audit failure'; end $$;
create trigger test_fail_audit before insert on private.audit_log for each row execute function test_support.fail_audit();
set local role service_role;
select throws_ok($$select test_support.run('start_attempt',jsonb_build_object('scheduledChallengeId',test_support.id('sc-survival')))$$,'P0001',null,'Start audit failure aborts command');
reset role;
select is((select count(*) from public.attempts),0::bigint,'Failed start leaves no attempt');
select is((select count(*) from private.attempt_sessions),0::bigint,'Failed start leaves no session');
select is((select count(*) from private.command_requests),0::bigint,'Failed start leaves no idempotency result');
drop trigger test_fail_audit on private.audit_log;
set local role service_role;
select test_support.run('start_attempt',jsonb_build_object('scheduledChallengeId',test_support.id('sc-survival')));
select test_support.run('prepare_interaction');
select throws_ok($$select test_support.run('receive_answer','{"answer":true,"submittedAt":"2000-01-01T00:00:00Z"}')$$,'22023',null,'Forged reception timestamp is rejected');
select throws_ok($$select test_support.run('receive_answer','{"answer":true,"playerId":"00000000-0000-0000-0000-000000000001"}')$$,'22023',null,'Command does not accept an actor identity');
select test_support.run('receive_answer','{"answer":true}');
select is((select private.read_evaluation_context((state->>'receiptId')::uuid,state->>'sessionToken')->'answer' from test_support.runtime),'true'::jsonb,'Evaluator reads persisted raw answer');
select is((select (private.read_evaluation_context((state->>'receiptId')::uuid,state->>'sessionToken')->>'payloadSchemaVersion')::integer from test_support.runtime),1,
  'Evaluator context includes the question payload schema version');
select is((select (private.read_evaluation_context((state->>'receiptId')::uuid,state->>'sessionToken')->>'itemConfigSchemaVersion')::integer from test_support.runtime),1,
  'Evaluator context includes the item config schema version');
select is((select (private.read_evaluation_context((state->>'receiptId')::uuid,state->>'sessionToken')->>'modeConfigSchemaVersion')::integer from test_support.runtime),1,
  'Evaluator context includes the mode config schema version');
select throws_ok($$select private.read_evaluation_context((state->>'receiptId')::uuid,repeat('z',40)) from test_support.runtime$$,'42501',null,'Wrong session cannot read evaluator context');
reset role;
select test_support.as_actor('member');
set local role service_role;
select throws_ok($$select private.read_evaluation_context((state->>'receiptId')::uuid,state->>'sessionToken') from test_support.runtime$$,'42501',null,'Other player cannot read receipt even knowing the token');
reset role;
select test_support.as_actor('owner');
set local role service_role;
select test_support.run('record_evaluation','{"status":"correct","points":50}');
select throws_ok($$select test_support.run('adjust_result','{"score":10,"reason":"forged admin"}')$$,'42501',null,'Ordinary player cannot adjust results');
reset role;
create trigger test_fail_audit before insert on private.audit_log for each row execute function test_support.fail_audit();
set local role service_role;
select throws_ok($$select test_support.run('take_over_attempt','{"newSessionToken":"tttttttttttttttttttttttttttttttttttttttt"}')$$,'55000','takeover_disabled','Cross-device takeover remains disabled even during a transient failure');
select throws_ok($$select test_support.run('complete_attempt','{"score":50}')$$,'P0001',null,'Completion audit failure rolls back accreditation');
reset role;
select is((select count(*) from private.attempt_sessions where revoked_at is null),1::bigint,'Failed completion retains the original active session');
select is((select count(*) from private.attempt_sessions),1::bigint,'Disabled takeover does not create a new session');
select is((select status from public.attempts),'in_progress','Failed completion does not close attempt');
select is((select count(*) from private.flash_point_entries),0::bigint,'Failed completion does not credit points');
drop trigger test_fail_audit on private.audit_log;
set local role service_role;
select test_support.run('complete_attempt','{"score":50}');
reset role;
select test_support.as_actor('superadmin');
create trigger test_fail_audit before insert on private.audit_log for each row execute function test_support.fail_audit();
set local role service_role;
select throws_ok($$select test_support.run('invalidate_attempt','{"reason":"test"}')$$,'P0001',null,'Invalidation audit failure rolls back reversal');
reset role;
select is((select status from public.attempts),'completed','Failed invalidation preserves completed status');
select is((select sum(amount) from private.flash_point_entries),50::bigint,'Failed invalidation preserves credited balance');
select is((select count(*) from private.flash_point_entries),1::bigint,'Failed invalidation leaves no reversal');
drop trigger test_fail_audit on private.audit_log;

-- Published per-question/per-level limits apply without a global deadline.
select test_support.as_actor('member');
set local role service_role;
select test_support.run('start_attempt',jsonb_build_object('scheduledChallengeId',test_support.id('sc-pyramid'),'sessionToken',repeat('p',40)));
select test_support.run('prepare_interaction');
reset role;
select is((select scope from private.attempt_timing_units where attempt_id=(select (state->>'attemptId')::uuid from test_support.runtime)),'level','Pyramid uses a level timing unit');
select is((select extract(epoch from deadline_at-started_at)*1000 from private.attempt_timing_units where scope='level'),60000::numeric,'Pyramid limit comes from published configuration');
create table test_support.saved as select state from test_support.runtime;
grant select on test_support.saved to service_role;
set local role service_role;
select test_support.run('prepare_interaction');
select is((select state->>'deadlineAt' from test_support.runtime),(select state->>'deadlineAt' from test_support.saved),'Preparation with a fresh key also preserves the clock');
select is((select state->>'presentedAt' from test_support.runtime),(select state->>'presentedAt' from test_support.saved),'Repeated preparation keeps original presentation');
select test_support.run('start_attempt',jsonb_build_object('scheduledChallengeId',test_support.id('sc-pyramid')));
select test_support.run('prepare_interaction');
select is((select state->>'deadlineAt' from test_support.runtime),(select state->>'deadlineAt' from test_support.saved),'Resume does not restart level time');
reset role;
update public.scheduled_challenges set status='closed' where id=test_support.id('sc-pyramid');
set local role service_role;
select lives_ok($$select test_support.run('receive_answer','{"answer":true}')$$,'An authorized started level continues after publication closes');
select test_support.run('record_evaluation','{"status":"incorrect","points":0}');
select test_support.run('abandon_attempt');
reset role;
select test_support.as_actor('superadmin');
set local role service_role;
select test_support.run('invalidate_attempt','{"reason":"uncredited abandonment"}');
reset role;
select is((select count(*) from private.flash_point_entries where attempt_id=(select (state->>'attemptId')::uuid from test_support.runtime)),0::bigint,'Invalidating an uncredited attempt creates no fictitious zero movement');
select test_support.as_actor('member');
set local role service_role;
select test_support.run('start_attempt',jsonb_build_object('scheduledChallengeId',test_support.id('sc-narrative'),'sessionToken',repeat('n',40)));
select is((select state->>'deadlineAt' from test_support.runtime),null::text,'Narrative has no global deadline');
select pg_sleep(0.02);
select test_support.run('prepare_interaction');
reset role;
select is((select scope from private.attempt_timing_units where attempt_id=(select (state->>'attemptId')::uuid from test_support.runtime)),'question','Narrative starts the question clock after scene transition');
select ok((select u.started_at>a.started_at from private.attempt_timing_units u join public.attempts a on a.id=u.attempt_id where a.id=(select (state->>'attemptId')::uuid from test_support.runtime)),'External transition time is outside the question interval');

-- Global deadline keeps advancing during external transitions. No new content after expiration.
set local role service_role;
select test_support.run('start_attempt',jsonb_build_object('scheduledChallengeId',test_support.id('sc-alphabet-fast'),'sessionToken',repeat('g',40)));
reset role;
select is((select extract(epoch from deadline_at-started_at)*1000 from public.attempts where id=(select (state->>'attemptId')::uuid from test_support.runtime)),100::numeric,'Global deadline is exactly the published limit from the persisted start');
set local role service_role;
select pg_sleep(0.12);
select throws_ok($$select test_support.run('take_over_attempt','{"newSessionToken":"hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh"}')$$,'55000','takeover_disabled','Takeover remains disabled after the global deadline');
select test_support.run('prepare_interaction');
select is((select last_result->'publicPayload' from test_support.runtime),'null'::jsonb,'Expired alphabet never delivers unvisited content');
select test_support.run('receive_answer','{"answer":null}');
select is((select (last_result->>'timeUsedMs')::bigint from test_support.runtime),0::bigint,'An unvisited expired letter adds no fictitious interaction duration');
select test_support.run('record_evaluation','{"status":"unanswered","points":0}');
select test_support.run('prepare_interaction');
select test_support.run('receive_answer','{"answer":null}');
select test_support.run('record_evaluation','{"status":"unanswered","points":0}');
select lives_ok($$select test_support.run('complete_attempt','{"score":0}')$$,'Expired global session still authorizes timeout cleanup and atomic completion');
reset role;
set constraints all immediate;
select * from finish();
rollback;
