begin;
set local search_path = public, extensions;
select no_plan();
-- @command-fixtures
select test_support.as_actor('member');
set local role service_role;
select lives_ok($$select private.prepare_attempt_session(test_support.id('sc-flash'))$$, 'Cookie preparation authorizes the publication');
reset role;
select is((select count(*) from public.attempts), 0::bigint, 'Cookie preparation consumes no attempt');
select is((select count(*) from private.attempt_timing_units), 0::bigint, 'Cookie preparation starts no clocks');
set local role service_role;
select test_support.run('start_attempt', jsonb_build_object('scheduledChallengeId',test_support.id('sc-flash')));
reset role;
update test_support.runtime set state=state || jsonb_build_object('startKey',last_input->>'idempotencyKey');
set local role service_role;
select test_support.run('prepare_interaction');
select test_support.run('receive_answer', '{"answer":"original received answer"}');
select is(private.read_recorded_evaluation((select (state->>'receiptId')::uuid from test_support.runtime), repeat('s',40)), null::jsonb, 'Received answer is initially unevaluated');
select test_support.run('recover_attempt');
select is((select last_result->>'recovered' from test_support.runtime),'false','Recovery reuses an existing receipt rather than making a null answer');
reset role;
select is((select answer from private.answer_receipts limit 1), '"original received answer"'::jsonb, 'Original payload survives the receive/evaluation cut');
select is((select count(*) from private.answer_receipts),1::bigint,'One durable receipt after recovery');
update public.room_memberships set status='removed', ended_at=clock_timestamp() where player_id=test_support.id('member');
set local role service_role;
select throws_ok($$select test_support.repeat_last()$$,'42501','not_authorized','Cached recovery cannot bypass revoked membership');
select throws_ok($$select private.read_attempt_recovery((select (state->>'attemptId')::uuid from test_support.runtime),repeat('s',40))$$,'42501','not_authorized','Recovery snapshot requires current membership');
reset role;
update public.room_memberships set status='active', ended_at=null where player_id=test_support.id('member');
update private.attempt_sessions set revoked_at=clock_timestamp();
set local role service_role;
select throws_ok($$select test_support.repeat_last()$$,'42501','session_revoked','Cached recovery cannot bypass controller revocation');
select throws_ok($$select private.start_attempt(jsonb_build_object('scheduledChallengeId',test_support.id('sc-flash'),'sessionToken',repeat('s',40),'idempotencyKey',(select state->>'startKey' from test_support.runtime)))$$,'42501','session_revoked','Cached start also requires the current controller');
reset role;
update private.attempt_sessions set revoked_at=null;
set local role service_role;
select test_support.run('record_evaluation','{"status":"correct","points":50}');
select is((private.read_recorded_evaluation((select (state->>'receiptId')::uuid from test_support.runtime),repeat('s',40))->>'points')::integer,50,'Replay reads the original evaluation');
select test_support.run('prepare_interaction');
select test_support.run('receive_answer','{"answer":true}');
select test_support.run('record_evaluation','{"status":"correct","points":50}');
reset role;
create function test_support.fail_accreditation() returns trigger language plpgsql as $$
begin raise exception 'injected accreditation failure'; end $$;
create trigger test_fail_accreditation before insert on private.flash_point_entries for each row execute function test_support.fail_accreditation();
set local role service_role;
select throws_ok($$select test_support.run('complete_attempt','{"score":100}')$$,'P0001','injected accreditation failure','Accreditation failure rolls back the whole close');
reset role;
select is((select status from public.attempts limit 1),'in_progress','Failed close preserves the active attempt');
select is((select count(*) from private.attempt_sessions where revoked_at is not null),0::bigint,'Failed close preserves its controller');
select is((select count(*) from private.flash_point_entries),0::bigint,'Failed close leaves no partial credit');
drop trigger test_fail_accreditation on private.flash_point_entries;
set local role service_role;
select test_support.run('complete_attempt','{"score":100}');
select is(test_support.repeat_last(),(select last_result from test_support.runtime),'Lost final confirmation repeats the exact result');
select is((private.read_completed_attempt((select (state->>'attemptId')::uuid from test_support.runtime))->'result'->>'score')::integer,100,'Final result does not require a controller cookie');
reset role;
select is((select count(*) from private.flash_point_entries where entry_type='accreditation'),1::bigint,'Final replay accredits once');
select is((select count(*) from private.attempt_answers),2::bigint,'Every receipt is evaluated once');
select test_support.as_actor('owner');
set local role service_role;
select is(private.read_completed_attempt((select (state->>'attemptId')::uuid from test_support.runtime)),null::jsonb,'Another account cannot recover the result');
reset role;
select test_support.as_actor('member');
update public.room_memberships set status='removed', ended_at=clock_timestamp() where player_id=test_support.id('member');
set local role service_role;
select is(private.read_completed_attempt((select (state->>'attemptId')::uuid from test_support.runtime)),null::jsonb,'A removed member cannot read the final result');
reset role;
select test_support.as_actor('owner');
set local role service_role;
select test_support.run('start_attempt', jsonb_build_object('scheduledChallengeId',test_support.id('sc-narrative'),'sessionToken',repeat('o',40)));
select test_support.run('prepare_interaction');
select test_support.run('abandon_attempt');
select is(private.read_abandoned_attempt((select (state->>'attemptId')::uuid from test_support.runtime))->'result',(select last_result from test_support.runtime),'Abandonment recovers its exact persisted result without a cookie');
reset role;
select is((select count(*) from private.flash_point_entries where attempt_id=(select (state->>'attemptId')::uuid from test_support.runtime)),0::bigint,'Abandonment replay never accredits');
select test_support.as_actor('member');
set local role service_role;
select is(private.read_abandoned_attempt((select (state->>'attemptId')::uuid from test_support.runtime)),null::jsonb,'Another account cannot recover abandonment');
reset role;
select * from finish();
rollback;
