import type { AnswerValue } from "@/types/contracts";
import type { ServerFlashQuestion } from "@/types/gameplay/challenge";
export type CompetitiveInputProps = {
  readonly question: ServerFlashQuestion;
  readonly questionNumber: number;
  readonly totalQuestions: number;
  readonly locked: boolean;
  readonly pendingAnswer?: AnswerValue | null;
  readonly submissionState: "idle" | "submitting" | "error";
  readonly submissionStatusVisible: boolean;
  readonly submissionError?: string;
  readonly onRetrySubmission?: () => void;
  readonly onSubmit: (answer: AnswerValue) => void;
  readonly onProgress: (answer: AnswerValue) => void;
  readonly onMiniWordleGuess: (guess: string) => void;
  readonly onLogicCodeAttempt: (code: string) => void;
  readonly queensState: "idle" | "submitting" | "error";
  readonly queensStatusVisible: boolean;
  readonly queensError?: string;
  readonly onQueensDraft: (queens: readonly number[]) => void;
  readonly onQueensValidate: (queens: readonly number[]) => void;
  readonly onRetryQueensValidation?: () => void;
  readonly wordSearchState: "idle" | "submitting" | "error";
  readonly wordSearchStatusVisible: boolean;
  readonly wordSearchError?: string;
  readonly lastWordSearchSelection?: {
    readonly startCell: number;
    readonly endCell: number;
    readonly correct: boolean;
  };
  readonly onWordSearchSelection: (startCell: number, endCell: number) => void;
  readonly onRetryWordSearch?: () => void;
  readonly onWordHashtagSwap: (fromCell: number, toCell: number) => void;
  readonly revealState: "idle" | "submitting" | "error";
  readonly revealStatusVisible: boolean;
  readonly revealError?: string;
  readonly onRevealProgressiveClue: () => void;
  readonly onRetryReveal?: () => void;
  readonly onTimeUp: () => void;
  readonly deadlineAt?: number | null;
  readonly presentedAt?: number | null;
  readonly livesRemaining?: number;
  readonly totalLives?: number;
  readonly presentation?: "default" | "pyramid";
  readonly showTimer?: boolean;
};
