import type { QuestionFormatGuide } from "../../catalogTypes";
import { SCORING_POLICIES } from "../../scoringPolicies";

export const guide = {
  id: "time-maze",
  slug: "laberinto-contrarreloj",
  name: "Laberinto contrarreloj",
  shortName: "Laberinto",
  summary: "Guiar una ficha desde la entrada hasta la salida antes de agotar el tiempo.",
  description: [
    "El jugador avanza por una cuadrícula de caminos y muros mediante una cruceta táctil o las flechas del teclado. Puede explorar, retroceder y corregir su ruta sin penalización.",
    "La ronda termina automáticamente al alcanzar la salida. El recorrido y los movimientos se conservan para compararlos con una ruta mínima en la revisión.",
  ],
  recommendations: [
    "Razonamiento espacial y orientación breve",
    "Desafíos especiales donde la ejecución sea tan importante como la solución",
    "Rondas táctiles con una condición de éxito inmediata",
  ],
  avoidWhen: [
    "La cuadrícula necesita más de nueve filas o columnas",
    "Los pasillos solo se distinguen mediante detalles visuales pequeños",
    "Se pretende evaluar precisión de arrastre en lugar de orientación",
  ],
  rules: [
    "Solo se puede avanzar a una casilla transitable ortogonalmente adyacente",
    "Se puede retroceder y los movimientos adicionales no reducen puntos",
    "Llegar a la salida envía automáticamente todo el recorrido",
    "El timeout conserva el camino realizado, pero concede cero puntos",
  ],
  authoringTips: [
    "Usa entre cinco y nueve filas y columnas",
    "Incluye una única entrada, una única salida y al menos una ruta válida",
    "Añade desvíos comprensibles sin depender de pasillos de un píxel",
    "Comprueba la ruta mínima y el tiempo necesario en un teléfono",
  ],
  accessibility: [
    "Evita el arrastre libre y ofrece cruceta y flechas del teclado",
    "Deshabilita direcciones bloqueadas y anuncia los muros al usar teclado",
    "Comunica entrada, salida, posición y recorrido con símbolos además de color",
    "Mantén el foco en el tablero y anuncia cada posición y número de movimientos",
  ],
  mediaSupport: ["Cuadrícula ortogonal de 5 × 5 a 9 × 9", "Símbolos de entrada y salida"],
  timing: {
    recommendedSeconds: "30–60 s",
    notes:
      "El límite debe permitir una exploración breve y algún retroceso sin convertir el reto en una prueba larga.",
  },
  scoring: SCORING_POLICIES["time-maze"],
  examples: [
    {
      title: "Salida relámpago",
      question: {
        id: "guide-time-maze",
        type: "time-maze",
        category: "Orientación",
        tags: {
          domains: ["geography", "mathematics"],
          topics: ["orientation", "spatial_logic_puzzles"],
          cognitiveSkills: ["problem_solving"],
          formatSkills: ["planning"],
        },
        question: "Guía el rayo desde S hasta E antes de que se agote el tiempo.",
        grid: { rows: 7, columns: 7 },
        cells: [
          "start",
          "path",
          "path",
          "path",
          "wall",
          "wall",
          "wall",
          "wall",
          "wall",
          "path",
          "wall",
          "path",
          "wall",
          "wall",
          "path",
          "path",
          "path",
          "wall",
          "path",
          "path",
          "path",
          "path",
          "wall",
          "wall",
          "wall",
          "path",
          "wall",
          "path",
          "path",
          "path",
          "path",
          "path",
          "path",
          "wall",
          "path",
          "path",
          "wall",
          "wall",
          "wall",
          "path",
          "path",
          "path",
          "path",
          "path",
          "path",
          "wall",
          "wall",
          "wall",
          "exit",
        ],
        timeLimit: 35,
        points: 150,
        explanation:
          "La ruta conecta la entrada superior izquierda con la salida inferior derecha. Se puede explorar cualquier desvío y retroceder sin perder puntos; solo importa resolver a tiempo.",
      },
    },
  ],
} satisfies QuestionFormatGuide<"time-maze">;
