/**
 * Types used by the scoring registry.
 *
 * The registry evaluates a fully resolved private question. That projection
 * is assembled only by practice fixtures or the server-side competitive
 * evaluator; public question payloads never reference this module.
 */
export type { AnswerResult, AnswerResultDetails, AnswerStatus } from "@/types/gameplay/result";
export type {
  AnagramQuestion,
  PracticeAnswerValue as ResolvedAnswerValue,
  PracticeAnswerValueOfType as ResolvedAnswerValueOfType,
  PracticeQuestion as ResolvedQuestion,
  QuestionOfType as ResolvedQuestionOfType,
  QuestionType,
  ClassificationAnswer,
  ClassificationQuestion,
  ConnectPairsAnswer,
  ConnectPairsQuestion,
  ErrorReconstructionAnswer,
  ErrorReconstructionQuestion,
  EscapeAnswer,
  EscapeQuestion,
  EstimationQuestion,
  FlashMemoryAnswer,
  FlashMemoryQuestion,
  HeatMapAnswer,
  HeatMapQuestion,
  AssignAllImageLabelingQuestion,
  ImageLabelingAnswer,
  ImageLabelingQuestion,
  LogicCodeQuestion,
  LogicMatrixQuestion,
  MatchingAnswer,
  MatchingQuestion,
  MemoryPairsAnswer,
  MemoryPairsQuestion,
  MiniNonogramAnswer,
  MiniNonogramQuestion,
  MiniSudokuAnswer,
  MiniSudokuQuestion,
  MiniWordleAnswer,
  MiniWordleQuestion,
  MultipleChoiceQuestion,
  OddOneOutQuestion,
  OrderingQuestion,
  PipesAnswer,
  PipesQuestion,
  ProgressiveCluesQuestion,
  ProgressiveImageQuestion,
  QueensAnswer,
  QueensQuestion,
  ShortTextQuestion,
  SimonSequenceAnswer,
  SimonSequenceQuestion,
  SlidingPuzzleAnswer,
  SlidingPuzzleQuestion,
  TimeMazeAnswer,
  TimeMazeQuestion,
  TrueFalseQuestion,
  WordHashtagAnswer,
  WordHashtagQuestion,
  WordSearchAnswer,
  WordSearchQuestion,
  ZipAnswer,
  ZipQuestion,
} from "@/types/gameplay/practice";
