import type { QuestionType } from "@/types/game";

export const QUESTION_FORMAT_LABELS = {
  "multiple-choice": "Elección",
  "odd-one-out": "Intruso",
  matching: "Emparejar",
  "true-false": "V/F",
  "short-text": "Texto",
  "progressive-clues": "Pistas",
  "progressive-image": "Imagen progresiva",
  "heat-map": "Mapa",
  "image-labeling": "Etiquetas",
  ordering: "Ordenar",
  classification: "Clasificar",
  "flash-memory": "Memoria",
  "simon-sequence": "Simon",
  "logic-matrix": "Matriz",
  "mini-sudoku": "Sudoku",
  "mini-nonogram": "Nonograma",
  "sliding-puzzle": "Puzzle",
  "error-reconstruction": "Reconstruir error",
  anagram: "Anagrama",
  "mini-wordle": "Mini-Wordle",
  "logic-code": "Código lógico",
  estimation: "Estimación",
} satisfies Record<QuestionType, string>;
