"use client";

import type { SuperadminPlayerCandidate } from "@/types/view-models";
import { Button } from "@/components/ui";
import styles from "./CreateRoomForm.module.css";

export type RoomMemberRow = { readonly id: number; readonly email: string; readonly role: "admin" | "member" | "spectator"; readonly candidate: SuperadminPlayerCandidate | null; readonly message: string };

export function RoomOwnerFields({ email, candidate, message, error, pending, onEmailChange, onLookup }: { readonly email: string; readonly candidate: SuperadminPlayerCandidate | null; readonly message: string; readonly error?: string; readonly pending: boolean; readonly onEmailChange: (value: string) => void; readonly onLookup: () => void }) {
  return <fieldset className={styles.fieldset}><legend>Propietario inicial</legend><div className={styles.inlineField}><input name="ownerEmail" type="email" value={email} onChange={(event) => onEmailChange(event.currentTarget.value)} placeholder="owner@ejemplo.com" required aria-invalid={Boolean(error || message)} /><Button type="button" variant="secondary" size="sm" onClick={onLookup} loading={pending}>Buscar</Button></div>{candidate ? <p className={styles.confirmed}>✓ {candidate.displayName}</p> : null}{message || error ? <small className={styles.error}>{message || error}</small> : null}</fieldset>;
}

export function RoomMemberFields({ members, error, pending, onAdd, onUpdate, onLookup, onRemove }: { readonly members: readonly RoomMemberRow[]; readonly error?: string; readonly pending: boolean; readonly onAdd: () => void; readonly onUpdate: (id: number, patch: Partial<RoomMemberRow>) => void; readonly onLookup: (member: RoomMemberRow) => void; readonly onRemove: (id: number) => void }) {
  return <fieldset className={styles.fieldset}><div className={styles.legendRow}><legend>Grupo inicial <em>(opcional)</em></legend><Button type="button" variant="secondary" size="sm" onClick={onAdd}>Añadir miembro</Button></div>{members.length === 0 ? <p className={styles.helper}>Puedes crear la sala solo con su propietario.</p> : null}<div className={styles.memberList}>{members.map((member) => <div className={styles.memberRow} key={member.id}><input type="hidden" name="memberEmail" value={member.email} readOnly /><input type="hidden" name="memberRole" value={member.role} readOnly /><input type="email" value={member.email} onChange={(event) => onUpdate(member.id, { email: event.currentTarget.value, candidate: null, message: "" })} placeholder="jugador@ejemplo.com" required aria-label="Email del miembro" /><select value={member.role} onChange={(event) => onUpdate(member.id, { role: event.currentTarget.value as RoomMemberRow["role"] })} aria-label="Rol del miembro"><option value="admin">Admin</option><option value="member">Member</option><option value="spectator">Spectator</option></select><Button type="button" variant="secondary" size="sm" onClick={() => onLookup(member)} loading={pending}>Buscar</Button><Button type="button" variant="secondary" size="sm" onClick={() => onRemove(member.id)}>Quitar</Button>{member.candidate ? <span className={styles.confirmed}>✓ {member.candidate.displayName}</span> : null}{member.message ? <small className={styles.error}>{member.message}</small> : null}</div>)}</div>{error ? <small className={styles.error}>{error}</small> : null}</fieldset>;
}
